name: hw-prim
version: '0.5.0.3'
synopsis: Primitive functions and data types
description: Please see README.md
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016-2018 John Ky
license: BSD3
github: haskell-works/hw-prim
homepage: http://github.com/haskell-works/hw-prim#readme
extra-source-files:
- README.md
ghc-options: -Wall
dependencies:
- base >=4 && <5
- bytestring
- mmap
- vector

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.AtIndex
  - HaskellWorks.Data.ByteString
  - HaskellWorks.Data.Char.IsChar
  - HaskellWorks.Data.Concat
  - HaskellWorks.Data.Container
  - HaskellWorks.Data.Decode
  - HaskellWorks.Data.Drop
  - HaskellWorks.Data.Empty
  - HaskellWorks.Data.Filter
  - HaskellWorks.Data.FromByteString
  - HaskellWorks.Data.FromForeignRegion
  - HaskellWorks.Data.Generate
  - HaskellWorks.Data.Head
  - HaskellWorks.Data.Length
  - HaskellWorks.Data.Naive
  - HaskellWorks.Data.Positioning
  - HaskellWorks.Data.Product
  - HaskellWorks.Data.Search
  - HaskellWorks.Data.Sign
  - HaskellWorks.Data.Snoc
  - HaskellWorks.Data.Take
  - HaskellWorks.Data.TreeCursor
  - HaskellWorks.Data.Uncons
  - HaskellWorks.Data.Unsign
  - HaskellWorks.Data.Vector.AsVector64
  - HaskellWorks.Data.Vector.BoxedVectorLike
  - HaskellWorks.Data.Vector.StorableVectorLike

tests:
  hw-prim-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - directory
    - exceptions
    - hedgehog
    - hspec
    - hw-hspec-hedgehog
    - hw-prim
    - vector

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - criterion
    - hw-prim
    - mmap

stability: Experimental
